apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jmeter-deployment-autoscaler
  namespace: bankingservices-sit
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-jmeter-deployment
  minReplicas: 1
  maxReplicas: 10  # Maximum number of pods based on CPU utilization
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70  # Target average CPU usage percentage
