apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-jmeter-deployment
  namespace: bankingservices-sit
spec:
  replicas: 1  # Initial replica count; HPA will manage scaling
  selector:
    matchLabels:
      app: jmeter
  template:
    metadata:
      labels:
        app: jmeter
      annotations:
        test-status: "not-started"  # Track if test has run
    spec:
      serviceAccountName: bankingservices-sa
      imagePullSecrets:
        - name: nexus
      containers:
        - name: jmeter
          image: sahabimgrepo.emiratesnbd.com:5000/git-jm-v1.2:v1
          command:
            - /bin/sh
            - '-c'
          args:
            - |
              if [ "$(cat /etc/podinfo/test-status)" = "completed" ]; then
                echo "Test already completed for pod $HOSTNAME. Exiting."
                exit 0
              else
                echo "Starting JMeter test" && \
                timestamp=$(date +%Y%m%d%H%M%S) && \
                git clone -b Development git@github.emiratesnbd.com:BankingServices/Jmeter-POC.git && \
                cp '/opt/apache-jmeter-5.5/Jmeter-POC/NodeJS_18_E_Notification_v3_1_5_X_F3_50TPS_24Oct2.jmx' /opt/apache-jmeter-5.5/ && \
                chmod 777 /opt/apache-jmeter-5.5/NodeJS_18_E_Notification_v3_1_5_X_F3_50TPS_24Oct2.jmx && \
                jmeter -n -t NodeJS_18_E_Notification_v3_1_5_X_F3_50TPS_24Oct2.jmx \
                -l /tmpfs/results_${timestamp}_$HOSTNAME.jtl \
                -j /tmpfs/results_${timestamp}_$HOSTNAME.log && \
                echo "JMeter test completed for pod $HOSTNAME, setting status to completed" && \
                echo "completed" > /etc/podinfo/test-status && \
                sleep 300 && \
                exit 0  # Exit after wait period to prevent restart
              fi
          resources:
            limits:
              cpu: '2'
              memory: 1300Mi
            requests:
              cpu: 10m
              memory: 1300Mi
          volumeMounts:
            - name: jmeter-pvc
              mountPath: /tmpfs
            - name: pod-info
              mountPath: /etc/podinfo
              readOnly: false
      volumes:
        - name: jmeter-pvc
          persistentVolumeClaim:
            claimName: jmeter-pvc
        - name: pod-info
          emptyDir: {}  # Temporarily stores test status for each pod
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - '-c'
              - |
                echo "Gracefully stopping JMeter pod $HOSTNAME"
