oc apply -f serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jmeter-sa
  namespace: bankingservices-sit


oc apply -f scale-specific-deployment-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bankingservices-sit
  name: jmeter-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["update"]
    resourceNames: ["test-jmeter-deployment"]  # Limits the permission to this specific deployment

scale-specific-deployment-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scale-specific-deployment-rolebinding
  namespace: bankingservices-sit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jmeter-role
subjects:
  - kind: ServiceAccount
    name: jmeter-sa
    namespace: bankingservices-sit

